// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqcMp2jWfMAwbzF0U07VhrxotLbTexHT4',
    appId: '1:683059527606:web:c90a98730c01dfa928cb17',
    messagingSenderId: '683059527606',
    projectId: 'bingogame-d3340',
    authDomain: 'bingogame-d3340.firebaseapp.com',
    storageBucket: 'bingogame-d3340.appspot.com',
    measurementId: 'G-4HD24N3VCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe3MWtMoi_iDR-tAtnp7_17L2t7vNf_0w',
    appId: '1:683059527606:android:a1f9ec9fd2722f8d28cb17',
    messagingSenderId: '683059527606',
    projectId: 'bingogame-d3340',
    storageBucket: 'bingogame-d3340.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBni1lY022z8ZeuGBhyv8SMRbc16-2SkAc',
    appId: '1:683059527606:ios:ecc45483c349f60128cb17',
    messagingSenderId: '683059527606',
    projectId: 'bingogame-d3340',
    storageBucket: 'bingogame-d3340.appspot.com',
    iosBundleId: 'com.example.bingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBni1lY022z8ZeuGBhyv8SMRbc16-2SkAc',
    appId: '1:683059527606:ios:ecc45483c349f60128cb17',
    messagingSenderId: '683059527606',
    projectId: 'bingogame-d3340',
    storageBucket: 'bingogame-d3340.appspot.com',
    iosBundleId: 'com.example.bingo',
  );
}
